In [1]:
import numpy as np

In [2]:
#To Create array 

arr=np.array([1,2,3] ) #list of array

In [3]:
print(arr)


[1 2 3]


In [4]:
#1d array= have on list 
#2d=multiple list 
#3d= list of list

In [7]:
arr=np.zeros([3,3])
arr1=np.ones([3,3])
arr2=np.full([3,3],4)

In [10]:
print(arr)

print(arr1)

print(arr2)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[4 4 4]
 [4 4 4]
 [4 4 4]]


In [13]:
#identity matrix:[[1. 0. 0.]
                 #[0. 1. 0.]
                  #[0. 0. 1.]]

arr=np.eye(3,3) #print identity matrix according to your order
print (arr)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
#add two number and provide another number:
arr=np.arange(1,100,10) #add each no with 10 and provide another array
print (arr)    


[ 1 11 21 31 41 51 61 71 81 91]


In [19]:
arr=np.linspace(1,100,15) #Betweem 1 and 100 it provide 10 arrays if we put 15 insted of 10 it provide list of 15 arrays
print (arr)

[  1.           8.07142857  15.14285714  22.21428571  29.28571429
  36.35714286  43.42857143  50.5         57.57142857  64.64285714
  71.71428571  78.78571429  85.85714286  92.92857143 100.        ]


In [38]:
#Checking array propoties

arr=np.array([ [ [1,2,3],[4,5,6],[7,8,9]] ,
              
              [[1,2,3],[4,5,6],[7,8,9]   ]   ])

shape=arr.shape
size=arr.size
ndim=arr.ndim
dtype=arr.dtype

In [39]:
print(shape) # print no of rows and column
print(size)  #Print how many no of array it contain
print(ndim)  #print ndim DIMENSION      #1darray= have on list  #2d=multiple list    #3d= list of list
print(dtype) #print data type of the array


(2, 3, 3)
18
3
int32


In [40]:
#Changing datatype in array:
#astype=change the datatype of array
#reshape = change the shape of array

In [43]:
arr=np.array([1,2,3,4]) 
reshape=arr.reshape(2,2) # change shape but order must be matched
print(reshape)

[[1 2]
 [3 4]]


In [49]:
arr=np.array([1,2,3,4]) 
print(arr.dtype)
astype=arr.astype("int64")# change the datatype of array
print(astype.dtype)


int32
int64
