In [1]:
import numpy as np

In [2]:
#vectorization:
#It allows arrays to peform operation in One step:

In [13]:
#without vectorization
arr=np.array([1,2,3,4,5])
arr1=[]

for num in arr:
    arr1.append(arr**2)
    break




In [14]:
arr1

[array([ 1,  4,  9, 16, 25])]

In [16]:
#With Vectorization:
arr=np.array([1,2,3,4,5])
arr1=arr**2
arr1
#here all the number of array is bodcast to create new array by squaring each no in array 
#Bodcastion doesnt take any extra memory and it is more fast and efficient method

array([ 1,  4,  9, 16, 25])

In [18]:
#boardcasting in 1d and 2d array
arr1=np.array([1,2,3,4,5])
arr2=np.array([[1,2,3,4,5] ,[6,7,8,9,10] ])
arr3=arr1**arr2
arr3

array([[      1,       4,      27,     256,    3125],
       [      1,     128,    6561,  262144, 9765625]])

In [33]:
# lets find normalization of data using bodcasting
arr = np.array([
    [72, 85, 91, 89, 77],
    [65, 90, 88, 86, 70],
    [80, 83, 85, 87, 90],
    [60, 70, 75, 78, 68]
])

mean=np.mean(arr, axis=0)
std=np.std(arr,  axis=0)

Normalization=(arr-mean)/std
np.set_printoptions(precision=3, suppress=True)  #this is use to print no of floating point and supression ensure all no is print in standard decimal form
Normalization



array([[ 0.365,  0.406,  1.039,  0.956,  0.087],
       [-0.564,  1.084,  0.54 ,  0.239, -0.726],
       [ 1.428,  0.135,  0.042,  0.478,  1.596],
       [-1.229, -1.625, -1.621, -1.673, -0.958]])