In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5])

In [3]:
arr

array([1, 2, 3, 4, 5])

In [4]:
arr.dtype

dtype('int32')

In [6]:
arr.astype('int64')

array([1, 2, 3, 4, 5], dtype=int64)

In [8]:
arr.dtype

dtype('int32')

In [9]:
arr.astype('float32')

array([1., 2., 3., 4., 5.], dtype=float32)

In [16]:
arr1=np.array(["orange","apple"], dtype='U10') #not recommend to use

In [17]:
arr1

array(['orange', 'apple'], dtype='<U10')

In [20]:
arr2=np.array([5+2j,6+44j], dtype="complex")
arr3=np.array([5+5j,6+4j], dtype="complex")

In [21]:
arr2+arr3

array([10. +7.j, 12.+48.j])

In [25]:
arr4=np.array([{'name':'ram'},{'age':12}], dtype="object") #not recommend

In [26]:
arr4

array([{'name': 'ram'}, {'age': 12}], dtype=object)