In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5,6,7])

In [4]:
np.mean(arr)#mean|

4.0

In [5]:
np.median(arr) #Median

4.0

In [8]:
np.sum(arr)#sum

28

In [9]:
np.min(arr)# Get min

1

In [10]:
np.max(arr)#max

7

In [11]:
np.std(arr)#standard deviation

2.0

In [13]:
np.var(arr)#variance

4.0

In [14]:
np.prod(arr)#product

5040

In [16]:
np.percentile(arr,4)#percentile

1.24

In [17]:
np.argmin(arr)#index of min

0

In [18]:
np.argmax(arr)#index of max

6

In [24]:
np.corrcoef(arr, arr)#coorelation cofficient


array([[1., 1.],
       [1., 1.]])

In [26]:
np.unique(arr)#only uniq element

array([1, 2, 3, 4, 5, 6, 7])

In [27]:
np.cumsum(arr)#cumlucative sum

array([ 1,  3,  6, 10, 15, 21, 28])

In [42]:
arr1 = np.linspace(3, 7, num=100) #evenly spread number
arr1

array([3.        , 3.04040404, 3.08080808, 3.12121212, 3.16161616,
       3.2020202 , 3.24242424, 3.28282828, 3.32323232, 3.36363636,
       3.4040404 , 3.44444444, 3.48484848, 3.52525253, 3.56565657,
       3.60606061, 3.64646465, 3.68686869, 3.72727273, 3.76767677,
       3.80808081, 3.84848485, 3.88888889, 3.92929293, 3.96969697,
       4.01010101, 4.05050505, 4.09090909, 4.13131313, 4.17171717,
       4.21212121, 4.25252525, 4.29292929, 4.33333333, 4.37373737,
       4.41414141, 4.45454545, 4.49494949, 4.53535354, 4.57575758,
       4.61616162, 4.65656566, 4.6969697 , 4.73737374, 4.77777778,
       4.81818182, 4.85858586, 4.8989899 , 4.93939394, 4.97979798,
       5.02020202, 5.06060606, 5.1010101 , 5.14141414, 5.18181818,
       5.22222222, 5.26262626, 5.3030303 , 5.34343434, 5.38383838,
       5.42424242, 5.46464646, 5.50505051, 5.54545455, 5.58585859,
       5.62626263, 5.66666667, 5.70707071, 5.74747475, 5.78787879,
       5.82828283, 5.86868687, 5.90909091, 5.94949495, 5.98989

In [51]:
arr=np.array([1,2,3,4,5,6,7])

In [52]:
np.exp(arr)#expontial 

array([   2.71828183,    7.3890561 ,   20.08553692,   54.59815003,
        148.4131591 ,  403.42879349, 1096.63315843])

In [53]:
arr=np.array([1,2,3,4,5,6,7])

In [54]:
np.log(arr)#natural logarithm

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015])

In [55]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [56]:
#these are the most important mathmatical operation done using numpy