In [9]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [10]:
ind=arr.flatten() #convert 2d array into 1d

In [11]:
ind

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
ind[1:7] #slice the array

array([2, 3, 4, 5, 6, 7])

In [13]:
ind[:4]

array([1, 2, 3, 4])

In [14]:
ind[2:]

array([3, 4, 5, 6, 7, 8, 9])

In [15]:
#slicing provide view not copy mean to say that if you change any value in slicing then the value of real array also change

In [16]:
b=ind[2:5]

In [17]:
b

array([3, 4, 5])

In [18]:
b[1]=444

In [19]:
b

array([  3, 444,   5])

In [20]:
ind

array([  1,   2,   3, 444,   5,   6,   7,   8,   9])

In [21]:
#we have to use .copy if we want to make slicing as copy

In [32]:
c=ind[2:6].copy()


In [33]:
print(c)

[  3 444   5   6]


In [34]:
c[1]=15

In [35]:
c

array([ 3, 15,  5,  6])

In [38]:
ind  #look .copy dont change the value because it is copy

array([  1,   2,   3, 444,   5,   6,   7,   8,   9])

In [39]:
#fancy indeximh and boolean masking

In [44]:
newarr=np.array([1,2,3,4,5,6,7,8,9,10])


In [50]:
newarr[[1,6,8]] #this will print the index values of 2,7,and 9th position and this is call boolean masking

array([2, 7, 9])

In [55]:
new=newarr[newarr>2]#this is called boolean masking 

In [56]:
new

array([ 3,  4,  5,  6,  7,  8,  9, 10])