In [4]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9] ])

In [5]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
arr.shape

(3, 3)

In [8]:
arr[1]   #one refers to second row cuz count start from 0

array([4, 5, 6])

In [12]:
arr[:,1]  # one after comma refers to f

array([2, 5, 8])

#[(0,0)(0,1)(0,2)
  (1,0) (1,1) (1,2)
   (2,0) (2,1) (2,2)] 
   

In [19]:
arr[1:,0:2]  #row starting from 1 and go up to last and column start from 0 and go up to 1 cuz one no be the provided number -1 is counted

array([[4, 5],
       [7, 8]])

In [21]:
arr1=np.array([[[1,2,3],[4,5,6],[7,8,9]] ,[[1,2,3],[4,5,6],[7,8,9]] ])

In [22]:
arr1

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [25]:
arr1[0] #first list is prented  due to 0

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
arr[:,:2,:2] # here i have done slicing of the 3d arrays 

array([[[1, 2],
        [4, 5]],

       [[1, 2],
        [4, 5]]])