In [1]:
import numpy as np

In [8]:
arr=np.arange(0,51,5)

In [9]:
arr

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [10]:
import random

In [18]:
arr1=np.random.randint(1,100,size=(3,3))

In [19]:
arr1

array([[13, 11, 32],
       [86, 81, 52],
       [47, 96, 22]])

In [20]:
arr3 = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

In [21]:
arr3

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [31]:
arr3[2,1]=0

In [32]:
arr3

array([[10, 20, 30],
       [40, 50, 60],
       [70,  0, 90]])

In [34]:
arr4=np.eye(3,3)

In [35]:
arr4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
arr5 = np.array([1, 2, 3, 4, 5])
min=np.min(arr5)
max=np.max(arr5)
normalization=(arr5-min)/(max-min)


In [37]:
normalization

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [46]:
a = np.array([2, 4, 6])
b = np.array([1, 2, 3])
print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [3 6 9]
Subtraction: [1 2 3]
Multiplication: [ 2  8 18]
Division: [2. 2. 2.]


In [47]:
arra = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
mean=np.mean(arra)
median=np.mean(arra)
std=np.std(arra)

In [48]:
std

2.581988897471611

In [49]:
arra1 = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

new=arra1.flatten()



In [50]:
new

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

even=arr=[arr % 2 ==0]

In [54]:
arr

[array([False,  True, False,  True, False,  True, False,  True, False,
         True])]

In [56]:
even

NameError: name 'even' is not defined