In [2]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
arr.shape

(3, 3)

In [5]:
#qus2
flo=np.array([1.1 , 2.2 , 3.3])

In [6]:
flo

array([1.1, 2.2, 3.3])

In [8]:
flo.dtype

dtype('float64')

In [16]:
newarr=flo.astype('int64')

In [19]:
newarr

array([1, 2, 3], dtype=int64)

In [23]:
#qs 3

In [24]:
arra=np.array([1,2,3,4,5,6])

In [29]:
arra[[1,3,5]]

array([2, 4, 6])

In [30]:
#qs4


In [31]:
arra=np.array([1,2,3,4,5,6,7,8,9])

In [32]:
arra.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
#qs5

In [34]:
arra=np.array([2,3,4,5,32,54,76,546,76,87,456,65])
new=arra[arra>50]

In [35]:
new

array([ 54,  76, 546,  76,  87, 456,  65])